name: Build Windows Artifact

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller

      - name: Build and package
        shell: pwsh
        run: |
          ./scripts/build.ps1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: program-windows
          path: |
            release/**
            *.zip
